"""Initial migration with all tables

Revision ID: f4b28ae95c8c
Revises: 
Create Date: 2025-12-06 09:27:49.309557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b28ae95c8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('students',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('mastery_score', sa.Integer(), nullable=True),
    sa.Column('topics_completed', sa.Integer(), nullable=True),
    sa.Column('at_risk', sa.Boolean(), nullable=True),
    sa.Column('sentiment_trend', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(length=80), nullable=True),
    sa.Column('preferred_voice', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_decision_logs',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('student_id', sa.String(length=80), nullable=False),
    sa.Column('student_input', sa.Text(), nullable=False),
    sa.Column('ai_output', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_conversations',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervention_flags',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('student_id', sa.String(length=80), nullable=False),
    sa.Column('student_name', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_sessions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_stats',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mastery', sa.Integer(), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('student_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_resources',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('uri', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('date_saved', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_messages',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('student_id', sa.String(length=80), nullable=False),
    sa.Column('teacher_name', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', name='userrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('attachment', sa.JSON(), nullable=True),
    sa.Column('conversation_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('module_id', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module_stats.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('module_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', name='userrole'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('live_session_id', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_items')
    op.drop_table('quiz_questions')
    op.drop_table('quiz_attempts')
    op.drop_table('messages')
    op.drop_table('teacher_messages')
    op.drop_table('study_resources')
    op.drop_table('module_stats')
    op.drop_table('live_sessions')
    op.drop_table('intervention_flags')
    op.drop_table('chat_conversations')
    op.drop_table('ai_decision_logs')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('users')
    # ### end Alembic commands ###
